name: Update Streak Stats

on:
  # run automatically every day at 03:00
  schedule:
    - cron: "0 3 * * *"

  # run any time this file is modified
  push:
    paths:
      - ".github/workflows/streak-stats.yml"
      - "README.md"

  # allows to manually run the job at any time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&theme=dark-minimalist&hide_border=true&date_format=j%20M%5B%20Y%5D&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
